security:
    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: username

    role_hierarchy:
        ROLE_MEMBER:     IS_AWAITING_VALIDATION
        ROLE_ADMIN:       ROLE_MEMBER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: /^, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                path:   /api/logout
                target: /api/spaceship
            json_login:
                check_path: /api/login

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 15